In [1]:
#Scipy usage and examples


In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [6]:
np.mgrid[0:3,0:5]

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [7]:
np.mgrid[0:5:9j,0:6:7j]

array([[[0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
        [0.625, 0.625, 0.625, 0.625, 0.625, 0.625, 0.625],
        [1.25 , 1.25 , 1.25 , 1.25 , 1.25 , 1.25 , 1.25 ],
        [1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875],
        [2.5  , 2.5  , 2.5  , 2.5  , 2.5  , 2.5  , 2.5  ],
        [3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125],
        [3.75 , 3.75 , 3.75 , 3.75 , 3.75 , 3.75 , 3.75 ],
        [4.375, 4.375, 4.375, 4.375, 4.375, 4.375, 4.375],
        [5.   , 5.   , 5.   , 5.   , 5.   , 5.   , 5.   ]],

       [[0.   , 1.   , 2.   , 3.   , 4.   , 5.   , 6.   ],
        [0.   , 1.   , 2.   , 3.   , 4.   , 5.   , 6.   ],
        [0.   , 1.   , 2.   , 3.   , 4.   , 5.   , 6.   ],
        [0.   , 1.   , 2.   , 3.   , 4.   , 5.   , 6.   ],
        [0.   , 1.   , 2.   , 3.   , 4.   , 5.   , 6.   ],
        [0.   , 1.   , 2.   , 3.   , 4.   , 5.   , 6.   ],
        [0.   , 1.   , 2.   , 3.   , 4.   , 5.   , 6.   ],
        [0.   , 1.   , 2.   , 3.   , 4.   , 5.   , 6. 

In [ ]:
#polynomials

In [11]:
from numpy import poly1d

In [13]:
p=poly1d([2,6,7])

In [15]:
print(p)

   2
2 x + 6 x + 7


In [16]:
print(p*p)
print(p.integ(k=9))
print(p.deriv())
p([4,0])

   4      3      2
4 x + 24 x + 64 x + 84 x + 49
        3     2
0.6667 x + 3 x + 7 x + 9
 
4 x + 6


array([63,  7])

In [17]:
#vectorize


In [35]:
def x(a,b):
    if a > b:
        return a - b
    else:
        return a + b

In [36]:
vec_x= np.vectorize(x)

In [37]:
vec_x([1,4,9],[9,3,1])

array([10,  1,  8])